### ISSUE TITLE
Lenguaje de programación a usar

### ISSUE THREAD

**Issue by hossam1522** [wickeet/Tripoli#6]
Buenas @wickeet, para poder trabajar sobre tu repositorio debemos ponernos de acuerdo sobre qué lenguaje de programación sería el más adecuado para este proyecto y el que deberíamos usar. ¿Qué opinas? ¿Tienes alguna idea?

**Comment by wickeet** [comment]
Buenas @hossam1522, la verdad había pensado en utilizar python pero estoy abierto a otros lenguajes. ¿Qué opinas?

**Comment by hossam1522** [comment]
Yo, personalmente, había pensado en usar Go, ya que es un lenguaje fácil de aprender y que maneja estas tareas de manera más eficiente que Python, además de ser fácilmente escalable. ¿Qué te parece?

**Comment by wickeet** [comment]
Ok, si ves que puede ser mejor Go no tengo problema en aprender un lenguaje nuevo
